# Generated by Django 3.2.5 on 2021-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='Ville_Code_postal',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Reseived', 'Order Reseived'), ('on the way', 'on the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing')], default='Order Reseived', max_length=22),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
