# Generated by Django 3.2.5 on 2021-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210717_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ville_Code_postal',
        ),
        migrations.AddField(
            model_name='product',
            name='numéro',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ville_code_postale',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Reseived', 'Order Reseived'), ('on the way', 'on the way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing')], default='Order Reseived', max_length=22),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
