# Generated by Django 3.2.5 on 2021-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210717_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Reseived', 'Order Reseived'), ('Order Completed', 'Order Completed'), ('on the way', 'on the way'), ('Order Canceled', 'Order Canceled')], default='Order Reseived', max_length=22),
        ),
    ]
