# Generated by Django 3.2.5 on 2021-07-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Reseived', 'Order Reseived'), ('Order Completed', 'Order Completed'), ('on the way', 'on the way'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled')], default='Order Reseived', max_length=22),
        ),
    ]
