# Generated by Django 3.2.5 on 2021-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210724_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Reseived', 'Order Reseived'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('on the way', 'on the way')], default='Order Reseived', max_length=22),
        ),
    ]
